### ISSUE TITLE
"brew tap filippo.io/age https://filippo.io/age" fails, can't reach repo.

### ISSUE THREAD

**Issue by sergeifilippov** [FiloSottile/age#124]
## Environment

* OS: MacOS Mojave 10.14.6 (18G3020)
* age version: n/a

## What happened

```
$ brew tap filippo.io/age https://filippo.io/age --debug
==> Tapping as full clone
==> Tapping filippo.io/age
Cloning into '/usr/local/Homebrew/Library/Taps/filippo.io/homebrew-age'...
remote: unknown package
fatal: repository 'https://filippo.io/age/' not found
Error: Failure while executing; `git clone https://filippo.io/age /usr/local/Homebrew/Library/Taps/filippo.io/homebrew-age` exited with 128.
/usr/local/Homebrew/Library/Homebrew/utils.rb:265:in `safe_system'
/usr/local/Homebrew/Library/Homebrew/tap.rb:273:in `install'
/usr/local/Homebrew/Library/Homebrew/cmd/tap.rb:65:in `tap'
/usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
```

**Comment by FiloSottile** [comment]
Thank you for reporting this! I had fucked up the redirects. Can you confirm it works now?

**Comment by FiloSottile** [comment]
Yay! https://github.com/FiloSottile/mostly-harmless/commit/08412c69f3b31bcaf918ebe6dac60f64038692ad#commitcomment-39244685
