### ISSUE TITLE
Installation on macOS failed

### ISSUE THREAD

**Issue by roastduckkiller** [FiloSottile/age#300]
## Environment

```
HOMEBREW_VERSION: 3.2.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 7d37d09709b6fbd5b89b468eb0b4438ffa0fb81c
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: aa4b76139630680884c2823727d7ffa773289fb0
Core tap last commit: 5 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 12.0.5 build 1205
Git: 2.30.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.4-x86_64
CLT: 12.5.1.0.1.1623191612
Xcode: 12.5.1
```

**I was trying to install age on my macbook pro, but installation failed and got following error message:**

```
brew install age
==> Downloading https://github.com/FiloSottile/age/archive/v1.0.0-rc.3.zip
Already downloaded: /Users/jiangs/Library/Caches/Homebrew/downloads/3da94ea27efb60f1321ee161792e28cb0f4cc8e6e2ce27fc5739b8d26e8e1029--age-1.0.0-rc.3.zip
==> go build -o /usr/local/Cellar/age/1.0.0-rc.3/bin -ldflags -X main.Version=v1.0.0-rc.3 filippo.io/age/cmd/...
Last 15 lines from /Users/jiangs/Library/Logs/Homebrew/age/01.go:
/usr/local/Cellar/age/1.0.0-rc.3/bin
-ldflags
-X main.Version=v1.0.0-rc.3
filippo.io/age/cmd/...
runtime/cgo
In file included from gcc_libinit.c:8:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/pthread.h:229:66: error: unknown type name 'size_t'
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/pthread.h:246:43: error: unknown type name 'size_t'
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/pthread.h:253:66: error: unknown type name 'size_t'
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/pthread.h:521:1: error: unknown type name 'size_t'
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/pthread.h:584:23: error: unknown type name 'size_t'
gcc_libinit.c:97:18: error: variable has incomplete type 'struct timespec'
gcc_libinit.c:97:9: note: forward declaration of 'struct timespec'
gcc_libinit.c:110:3: error: implicit declaration of function 'nanosleep' is invalid in C99 [-Werror,-Wimplicit-function-declaration]

Do not report this issue to Homebrew/brew or Homebrew/core!

Traceback (most recent call last):
	26: from /usr/local/Homebrew/Library/Homebrew/build.rb:229:in `<main>'
	25: from /usr/local/Homebrew/Library/Homebrew/build.rb:133:in `install'
	24: from /usr/local/Homebrew/Library/Homebrew/utils.rb:550:in `with_env'
	23: from /usr/local/Homebrew/Library/Homebrew/build.rb:138:in `block in install'
	22: from /usr/local/Homebrew/Library/Homebrew/formula.rb:1260:in `brew'
	21: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2375:in `stage'
	20: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `stage'
	19: from /usr/local/Homebrew/Library/Homebrew/resource.rb:91:in `stage'
	18: from /usr/local/Homebrew/Library/Homebrew/resource.rb:116:in `unpack'
	17: from /usr/local/Homebrew/Library/Homebrew/resource.rb:199:in `mktemp'
	16: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:63:in `run'
	15: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:63:in `chdir'
	14: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:63:in `block in run'
	13: from /usr/local/Homebrew/Library/Homebrew/resource.rb:117:in `block in unpack'
	12: from /usr/local/Homebrew/Library/Homebrew/download_strategy.rb:102:in `stage'
	11: from /usr/local/Homebrew/Library/Homebrew/download_strategy.rb:115:in `chdir'
	10: from /usr/local/Homebrew/Library/Homebrew/download_strategy.rb:115:in `chdir'
	 9: from /usr/local/Homebrew/Library/Homebrew/resource.rb:121:in `block (2 levels) in unpack'
	 8: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2395:in `block in stage'
	 7: from /usr/local/Homebrew/Library/Homebrew/utils.rb:550:in `with_env'
	 6: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2396:in `block (2 levels) in stage'
	 5: from /usr/local/Homebrew/Library/Homebrew/formula.rb:1267:in `block in brew'
	 4: from /usr/local/Homebrew/Library/Homebrew/build.rb:178:in `block (2 levels) in install'
	 3: from /usr/local/Homebrew/Library/Taps/filippo.io/homebrew-age/HomebrewFormula/age.rb:18:in `install'
	 2: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2166:in `system'
	 1: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2166:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2230:in `block in system': Failed executing: go build -trimpath -o /usr/local/Cellar/age/1.0.0-rc.3/bin -ldflags -X\ main.Version=v1.0.0-rc.3 filippo.io/age/cmd/... (BuildError)
	5: from /usr/local/Homebrew/Library/Homebrew/brew.rb:155:in `<main>'
	4: from /usr/local/Homebrew/Library/Homebrew/brew.rb:167:in `rescue in <main>'
	3: from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:509:in `dump'
	2: from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:455:in `issues'
	1: from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:459:in `fetch_issues'
/usr/local/Homebrew/Library/Homebrew/utils/github.rb:60:in `issues_for_formula': undefined method `full_name' for nil:NilClass (NoMethodError)
```

**Comment by FiloSottile** [comment]
It looks like your Command Line Tools installation is broken, it doesn't look like it's an age-specific issue.
